-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 20-10-2021 a las 01:44:55
-- Versión del servidor: 10.4.21-MariaDB
-- Versión de PHP: 8.0.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `proyectofinal`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `carrusel`
--

CREATE TABLE `carrusel` (
  `id` int(11) NOT NULL,
  `imagen` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `carrusel`
--

INSERT INTO `carrusel` (`id`, `imagen`) VALUES
(1, 'img/Farcry6.jpg'),
(2, 'img/Vanguard.jpg'),
(3, 'img/Village.jpg'),
(4, 'img/Haloinfinite.png');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `productos`
--

CREATE TABLE `productos` (
  `id` int(11) NOT NULL,
  `producto` varchar(20) DEFAULT NULL,
  `descripcion` text NOT NULL,
  `tipo` varchar(11) NOT NULL,
  `precio` int(11) NOT NULL,
  `imagen` varchar(100) NOT NULL,
  `detalles` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `productos`
--

INSERT INTO `productos` (`id`, `producto`, `descripcion`, `tipo`, `precio`, `imagen`, `detalles`) VALUES
(1, 'PS5', 'Consola Sony Playstation 5 Ps5 825Gb Lector De Disco.', 'consola', 499, 'img/PS5.jpg', 'Con tu consola PlayStation 5 tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.\r\n\r\nPlayStation renovó las expectativas del mundo virtual con esta nueva consola y su gran rendimiento. Cuenta con una interfaz de usuario más rápida y fácil de navegar que en anteriores modelos. Además, podrás jugar durante horas desafiando a millones de contrincantes alrededor del mundo que esperan nuevos retos.\r\n\r\nCalidad de otro nivel\r\nSe considera que esta consola es de las mejores dentro del mercado, dado que presenta una resolución de hasta 4K.\r\n\r\nAdemás, el control DualSense para PS5 combina estilo y tecnología para que jugar sea más cómodo e interactivo para todos sus jugadores.\r\n\r\nAdaptada a tus necesidades\r\nGuarda tus apps, fotos, videos y mucho más en el disco duro, que cuenta con una capacidad de 825 GB.\r\nAl contar con un procesador de 8 núcleos y uno gráfico, brinda una experiencia dinámica, respuestas ágiles, y transiciones fluidas de imágenes en alta definición.\r\nPor otro lado, tiene puerto USB y salida HDMI, que permiten conectar accesorios y cargar la batería de tu control mientras juegas.\r\n\r\nVas a poder reproducir música, ver tus películas y series favoritas a través de las aplicaciones descargables. '),
(2, 'Xbox Series X', 'Consola Xbox Series X 1Tb Microsoft.', 'consola', 499, 'img/Xboxseriesx.png', 'Con tu consola Xbox Series tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.\r\n\r\nLa nueva generación de consolas está comandada por la Xbox Series que llegó al mercado para sorprender a todos. Su potencia y alto rendimiento te permitirá reducir las horas de descarga de juegos y contenido de manera considerable en comparación con otras consolas. Además, vas a poder jugar durante horas mientras te diviertes con jugadores de todo el mundo.\r\n\r\nAdaptada a tus necesidades\r\nGuarda tus apps, fotos, videos y mucho más en el disco duro, que cuenta con una capacidad de 1 TB.\r\nAl contar con un procesador de 8 núcleos y uno gráfico, brinda una experiencia dinámica, respuestas ágiles, y transiciones fluidas de imágenes en alta definición.\r\nPor otro lado, tiene puerto USB y salida HDMI, que permiten conectar accesorios y cargar la batería de tu control mientras juegas.\r\n\r\nVas a poder reproducir música, ver tus películas y series favoritas a través de las aplicaciones descargables. '),
(4, 'GTA V', 'Grand Theft Auto V: Premium Online Edition Rockstar Games.', 'juego', 10, 'img/GTAV.jpeg', 'Al comprar Grand Theft Auto V: Edición online Premium te sumergirás en el inmenso mundo de GTA online con un montón de contenido. No sólo obtendrás el juego base, Grand Theft Auto V, sino que también encontrarás Criminal Enterprise Starter Pack. ¡Vale la pena adentrarte en él!\r\n\r\nGrand Theft Auto V - Criminal Enterprise Starter Pack es una de las mejores maneras de comenzar su viaje de GTA V online. Con este paquete exclusivo, su personaje en el juego obtendrás instantáneamente contenido estimado en más de diez millones de GTA $, ¡y un bono adiciona!'),
(5, 'Far Cry 6', 'FAR CRY 6 XBOX LIVE Key GLOBAL.', 'juego', 60, 'img/FARCRY6.jpeg', '¡Ten la oportunidad de experimentar la sexta entrega de la serie de acción en primera persona de mundo abierto comprando el código Far Cry 6 Xbox One! El editor y desarrollador Ubisoft debería entregar un juego que utilice todas las mejores características de sus predecesores y los supere en todos los aspectos. No te preocupes si no has jugado a Far Cry antes: cada juego presenta su propia historia y personajes por separado para que no te sientas perdido incluso como un recién llegado. Al mismo tiempo, los veteranos de la serie experimentarán un juego de Far Cry que tiene un alto potencial de convertirse en tu nuevo favorito.'),
(6, 'FIFA 22', 'FIFA 22 (PC) Código de Origin GLOBAL.', 'juego', 50, 'img/FIFA22.jpeg', 'Experimenta el siguiente nivel de inmersión con el nuevo juego de FIFA La fecha de lanzamiento de FIFA 22 es el 2 de octubre, y Electronic Arts promete un montón de nuevos contenidos e innovaciones para los entusiastas de esta larga serie de simulación deportiva. Todos los modos se han ajustado para ofrecer un mejor rendimiento, se han realizado cambios fundamentales en la jugabilidad para que todo sea más realista, y una impresionante lista de más de 17.000 jugadores y más de 700 equipos está lista para luchar por la victoria en el campo. Pon a prueba tus habilidades en una de las 30 competiciones más importantes del mundo, enfréntate a otros jugadores online o construye una exitosa carrera en el mundo del fútbol con FIFA 22 Código de Origen.'),
(7, 'PS5 Digital Edition', 'Sony PlayStation 5 825GB Digital Edition color blanco y negro.\r\n', 'oferta', 350, 'img/Ps5digital.PNG', 'Con tu consola PlayStation 5 tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.\r\n\r\nPlayStation renovó las expectativas del mundo virtual con esta nueva consola y su gran rendimiento. Cuenta con una interfaz de usuario más rápida y fácil de navegar que en anteriores modelos. Además, podrás jugar durante horas desafiando a millones de contrincantes alrededor del mundo que esperan nuevos retos.\r\n\r\nCalidad de otro nivel\r\nSe considera que esta consola es de las mejores dentro del mercado, dado que presenta una resolución de hasta 4K.\r\n\r\nAdemás, el control DualSense para PS5 combina estilo y tecnología para que jugar sea más cómodo e interactivo para todos sus jugadores.\r\n\r\nAdaptada a tus necesidades\r\nGuarda tus apps, fotos, videos y mucho más en el disco duro, que cuenta con una capacidad de 825 GB.\r\nAl contar con un procesador de 8 núcleos y uno gráfico, brinda una experiencia dinámica, respuestas ágiles, y transiciones fluidas de imágenes en alta definición.\r\nPor otro lado, tiene puerto USB y salida HDMI, que permiten conectar accesorios y cargar la batería de tu control mientras juegas.\r\n\r\nVas a poder reproducir música, ver tus películas y series favoritas a través de las aplicaciones descargables. '),
(8, 'Minecraft', 'Minecraft: Java Edition web oficial Key GLOBAL.', 'oferta', 20, 'img/MINECRAFT.jpeg', 'Cuando hablamos de Minecraft, es difícil decir por dónde empezar. Este videojuego es un sandbox y fue creado por Markus Persson y desarrollado posteriormente por Mojang. Es una reminiscencia de los juegos de 8 bits, donde tu creatividad es el único factor limitante. Imagina que juegas con legos: es lo mismo con Minecraft, ¡vas a construir con bloques el mundo que siempre has soñado!'),
(10, 'Darksouls III', 'Dark Souls 3 Steam Clave GLOBAL.', 'oferta', 12, 'img/DARKSOULS3.jpg', 'Dark Souls III key ofrece un RPG de acción oscuro y enrevesado de los desarrolladores FromSoftware. El fuego casi se ha extinguido, y allá donde el fuego muere viene la oscuridad que sumerge a la humanidad profunda en sí misma, ¿puedes mantener vivo el fuego? ¡Esta misión ha caído en tus incansables hombros!'),
(29, 'PS4', 'Sony PlayStation 4 Slim 1TB color negro azabache', 'consola', 400, 'img/PS4.jpg', 'Con tu consola PlayStation 4 tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.  Con la consola PlayStation 4, líder mundial en ventas durante años, podrás gozar de horas de juego y una excelente navegabilidad para disfrutar de películas, series y contenido online.  Gracias a sus pequeñas dimensiones, su consumo energético es reducido, lo que la convierte en un producto económico y accesible.  No solo esto, el control DualShock combina funciones revolucionarias y sin precedentes mientras conserva precisión, comodidad y exactitud en cada movimiento.   Adaptada a tus necesidades Guarda tus apps, fotos, videos y mucho más en el disco duro, que cuenta con una capacidad de 1 TB. Al contar con un procesador de 8 núcleos y uno gráfico, brinda una experiencia dinámica, respuestas ágiles, y transiciones fluidas de imágenes en alta definición. Por otro lado, tiene puerto USB y salida HDMI, que permiten conectar accesorios y cargar la batería de tu control mientras juegas.  Vas a poder reproducir música, ver tus películas y series favoritas a través de las aplicaciones descargables. '),
(32, 'Xbox Series S', 'Consola XBOX Series S 512 SSD + Control.', 'consola', 299, 'img/Xbox series s.jpg', 'Con tu consola Xbox Series tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos. La nueva generación de consolas está comandada por la Xbox Series que llegó al mercado para sorprender a todos. Su potencia y alto rendimiento te permitirá reducir las horas de descarga de juegos y contenido de manera considerable en comparación con otras consolas. Además, vas a poder jugar durante horas mientras te diviertes con jugadores de todo el mundo. Adaptada a tus necesidades Guarda tus apps, fotos, videos y mucho más en el disco duro, que cuenta con una capacidad de 512 GB. Al contar con un procesador de 8 núcleos y uno gráfico, brinda una experiencia dinámica, respuestas ágiles, y transiciones fluidas de imágenes en alta definición. Por otro lado, tiene puerto USB y salida HDMI, que permiten conectar accesorios y cargar la batería de tu control mientras juegas. Vas a poder reproducir música, ver tus películas y series favoritas a través de las aplicaciones descargables.'),
(33, 'Nintendo Switch', 'Nintendo Switch 32GB Standard color rojo neón, azul neón y negro', 'consola', 399, 'img/Nintendo Switch.jpg', 'Con tu consola Switch tendrás entretenimiento asegurado todos los días. Su tecnología fue creada para poner nuevos retos tanto a jugadores principiantes como expertos.  Switch se convirtió en una de las consolas más versátiles del mercado gracias a su uso portátil y de sobremesa. Nintendo desarrolló este modelo con el objetivo de tener todas las comodidades de la tecnología de elite en un aparato portátil con el que podrás jugar y disfrutar de diverso contenido online.  Nintendo Switch es una consola desmontable, que puede usarse en modo portátil, sobremesa o en la TV; esto te brindará la posibilidad de utilizarla donde quieras y compartir sus controles.  Los Joy-con cuentan con botones especiales para realizar print de pantalla. Además, posee una cámara infrarroja que puede leer la distancia respecto a los objetos e incluso detectar formas.  Adaptada a tus necesidades Guarda tus apps, fotos, videos y mucho más en el disco duro, que cuenta con una capacidad de 32 GB. Por otro lado, tiene puerto USB y salida HDMI, que permiten conectar accesorios y cargar la batería de tu control mientras juegas.  Vas a poder reproducir música, ver tus películas y series favoritas a través de las aplicaciones descargables.'),
(34, 'PS4 Pro', 'PS4 Pro 1tb + Control Original PlayStation 4 Consola 4k', 'consola', 430, 'img/PS4 Pro.jpg', 'Juegos y entretenimiento en 4K  Disfruta de los juegos más populares y de las exclusivas de PlayStation en la fantástica resolución 4K, y transmite tu entretenimiento favorito con un increíble nivel de detalle en los servicios compatibles con 4K.  Mayor velocidad de fotogramas  Disfruta de un mayor nivel de inmersión en los títulos de PS4 más vertiginosos y explosivos con la velocidad de fotogramas mejorada en una gama de juegos mejorados para PS4 Pro, que es posible gracias a la potencia adicional de PS4 Pro.  El doble de potencia que PS4  PS4 Pro cuenta con una GPU el doble de potente que la PS4 estándar, para que disfrutes de gráficos increíblemente nítidos, una mecánica de juego más fluida y tiempos de carga reducidos en los juegos mejorados para PS4 Pro**.  Tecnología HDR  Disfruta de colores y detalles más realistas y llamativos en todos los aspectos de tu experiencia de juego al jugar en un televisor compatible con HDR. Mejorados para PS4 Pro'),
(35, 'Xbox One S', 'Consola Xbox One S De 1t + 2 Controles. Garantia De 1 Año', 'consola', 250, 'img/Xbox One S.jpg', 'Consola Xbox One S de 1Tb + 2 controles + HDMI + 4K  Lo mejor en entretenimiento en 4K Streaming en 4K Haz streaming de video Ultra HD 4K en Netflix y más. Blu-ray 4K Disfruta de las películas con lujo de detalle gracias al Blu-ray™ 4K Ultra HD. Sonido espacial Haz que tus juegos y películas cobren vida con el sonido envolvente Dolby Atmos y DTS:X.5 Aplicaciones de entretenimiento interminables Disfruta de tus aplicaciones favoritas, como YouTube, Spotify y muchas más.'),
(36, 'Back 4 Blood', 'Back 4 Blood (PC) Steam Key EUROPE', 'juego', 70, 'img/Back 4 Blood.jpg', 'Los creadores del clásico de culto Left 4 Dead regalan a sus fans otro emocionante shooter de zombis cooperativo. Back 4 Blood, el proyecto conjunto de Turtle Rock Studios y Warner Bros. Games, es una experiencia de acción cargada de adrenalina en la que el destino de la humanidad depende de ti y de tus amigos. Una mortífera infestación de parásitos ha devastado rápidamente nuestra civilización y lo que queda se convierte en su fuente de sustento. Los Ridden son feroces y ágiles, pero un grupo de supervivientes inmunes y armados con armas letales podría ser capaz de suprimir estas macabras cáscaras de antiguos humanos. ¡Compra Back 4 Blood Código de Steam y lleva la sangrienta lucha al enemigo!  Características del juego de Back 4 Blood La humanidad está al borde de la extinción, pero con agallas y perseverancia, podrías cambiar el destino a tu favor. Con el código de Back 4 Blood, puedes esperar:  • Campaña cooperativa. 4 jugadores pueden unirse para salvar al mundo de la devastación total el enemigo evoluciona constantemente, así que prepárate para peligrosas sorpresas; • 8 limpiadores personalizables. Elige un personaje, escoge un arma y un objeto y adéntrate en zonas infestadas con un objetivo en mente: erradicar a los muertos; • Frenesí multijugador. Sigue siendo un Limpiador o encarna al enemigo y juega con o contra tus amigos en PVP: cada bando tiene habilidades, armas e incluso especialidades únicas; • Cada sesión es diferente. El sistema de cartas roguelike cambia la forma en que te enfrentas a las batallas: crea mazos personalizados, lanza diferentes construcciones y participa en desafiantes escaramuzas; • Precio barato de Back 4 Blood..'),
(37, 'Monster Hunter World', 'Monster Hunter: World Steam Key EUROPE', 'juego', 24, 'img/Monster Hunter World.jpg', 'Monster Hunter: World key ofrece un juego de acción RPG desarrollado por Capcom. Atraviesa el Nuevo Mundo, explora su ecosistema y siempre estate atento a las monstruosas criaturas con las que compartes el mundo. Hay wyverns y dragones como nunca antes los habías visto. Este juego no es solo cuestión de supervivencia, hay retos esperandote, honor y gloria que ganar, y cada cazador de monstruos sabe que esto es lo importante.  Las criaturas Monster Hunter World key te lleva a vivir una aventura extraordinaria. Prepárate a enfrentarte a Jagra, wyverns parecidos a lagartos con la postura de un lobo. Esta criatura puede devorar a su presa entera y consigue hacerse más fuerte una vez lleno. O Radobaan, criatura que utiliza distintos huesos para cubrir su cuerpo y que puede llegar a tener malas pulgas. Y Nergigante.... No querrás encontrar con él. Y estos son solo unas pocas criaturas que encontrarás alrededor del mundo de Moster Hunter.'),
(38, 'Dark Souls Remastere', 'Dark Souls: Remastered Steam Clave GLOBAL', 'juego', 23, 'img/Dark Souls Remastered.jpg', 'Dark Souls: Remastered es la reencarnación 4k HDR del juego original de Dark Souls desarrollado por Bandai Namco. Junto a gráficos mejorados, calidad y mejores FPS, también tendrás acceso al juego básico de Dark Souls, junto al DLC Artorias del Abismo y el modo multijugador expandido, donde hasta 6 personas pueden participar en peligrosos retos juntos.   Dark Souls es conocido por su extraordinaria complejidad, terrenos sin piedad, y el hecho de que la suerte nunca está de tu lado. El juego favorece un método fundamental de prueba y error, donde uno debe fallar numerosas veces en cada paso para conseguir no cometer ningún error y completar una serie de objetivos con excelencia.  '),
(39, 'Cyberpunk 2077', 'Cyberpunk 2077 GOG Clave GLOBAL', 'oferta', 19, 'img/Cyberpunk 2077.jpg', 'Compra Cyberpunk 2077 key y sumérgete en un mundo abierto donde serás capaz de explorar Night City: una enorme, distópica metrópolis, donde todos están obsesionados con tecnología sci-fi y modificación corporales. Esta experiencia RPG de CD Project RED te dará los controles de V, una absoluta bestia humana, quién (como muchos otros) está obsesionado con adquirir un implante en especial, uno que otorga inmortalidad.  Night City Night City va más allá de lo entendible cuando hablamos de escala y tamaño. Además, cada habitante allí vive sus propias vidas, independientemente de tu existencia. Compra Cyberpunk 2077 key si buscas una historia de aventura que también te permitirá salirte del guión como quieras, y aún así llegar al final. El juego ofrece numerosos finales, y así, cada decisión tiene gran importancia.  Armas y habilidades Mientras que Cyberpunk no es necesariamente una experiencia FPS ya que tendrá numerosas cutscenes, y podrás conducir varios vehículos desde una perspectiva de tercera persona, no hay duda: en ocasiones pensarás que estás en un juego FPS de guerra total. El juego ofrece frenética, caótica y alocada acción con una plétora de devastadoras armas a tu disposición. Compra Cyberpunk 2077 key y conviértete en un artesano de la guerra. ¡Además, numerosas habilidades se unen a la mezcla!'),
(40, 'Red Dead Redemption2', 'Red Dead Redemption 2 (PC) Green Gift Key GLOBAL', 'juego', 33, 'img/Red Dead Redemption 2.jpg', 'Red Dead Redemption 2 es un videojuego de acción-aventura de temática western ambientado en un entorno de mundo abierto y jugado desde una perspectiva en tercera persona (con posibilidad de primera persona e incluso eliminar el HUD), con componentes para un jugador y multijugador en línea. El videojuego presenta novedades frente a su antecesor. El personaje puede nadar, usar un arco y una flecha, empuñar dos revólveres o usar una canoa; entre otras actividades. También usar una cámara fotográfica, e incluso hacerse selfies[2]. La vida silvestre y la caza en el juego también han mejorado.'),
(41, 'Horizon Zero Dawn', 'Horizon Zero Dawn: Complete Edition Steam Key GLOBAL\r\n', 'juego', 19, 'img/Horizon Zero Dawn.jpg', '¡Una de las exclusivas de PlayStation 4 más aclamadas por la crítica ahora llega a PC y Horizon: Zero Dawn Steam puede ser tu oportunidad de tener una experiencia de juego de proporciones épicas! Originalmente lanzado en 2017 para la PS4, Horizon: Zero Dawn fue desarrollado por Guerrilla Games, un estudio detrás de una serie de FPS de ciencia ficción exclusiva de PS4 tan notable como Killzone. ¡Ahora los jugadores de PC tendrán la oportunidad de disfrutar de la Edición Completa de Guerrilla Games en el género RPG de acción y aventura donde los creadores vuelven sorprender!  Historia y escenario Horizon Zero Dawn: Edición Completa se destaca entre los juegos contemporáneos por su entorno único y original que combina elementos de ciencia ficción, post-apocalipsis y explora los temas del tribalismo. El código CD Horizon: Zero Dawn Steam promete una campaña inmersiva que sigue la historia de la joven marginada llamada Aloy, y su búsqueda para descubrir los misterios del pasado y salvar a la humanidad de una inminente amenaza existencial.'),
(42, 'F1 2021', 'F1 2021 Código de Steam GLOBAL', 'juego', 59, 'img/F1 2021.jpg', '¡El juego oficial del Campeonato mundial de Fórmula 1 está de vuelta y es mejor que nunca! Los legendarios desarrolladores de juegos de carreras Codemasters y el famoso estudio Electronic Arts se enorgullecen de presentar la nueva iteración de su larga serie de simuladores de carreras que abordará los eventos del Campeonato de F1 2021. La fecha de lanzamiento de F1 2021 está prevista para el 2021-07-26. Los jugadores serán testigos de una nueva y emocionante historia, un modo carrera para dos jugadores y un montón de nuevas características e innovaciones que elevarán la experiencia de la F1 a nuevos niveles. Sumérgete en competiciones llenas de adrenalina mientras te enfrentas a diez equipos emblemáticos de la temporada 2021. Compra el código de Steam de F1 2021: ¡Elige tu vehículo, acelera y deja marca en los circuitos mientras te robas el primer puesto en el Campeonato 2021!'),
(43, 'Far Cry 5', 'Far Cry 5 Uplay Clave EUROPA', 'juego', 15, 'img/Far Cry 5.jpg', 'Far Cry 5 es un juego FPS de acción y aventura en mundo abierto desarrollado por Ubisoft. Es un sucesor por libre de sus precuelas, con una historia ramificada, misiones secundarias, modo cooperativo, editor de mapa ¡y un multijugador competitivo! El juego ofrece una narrativa excitante con uno de los mejores enemigos de la saga, muchos giros de guión, ¡y más!  Valor del dinero  Con respecto al precio de Far Cry 5, pagas por la calidad de un AAA y eso es lo que recibes. Hay un motivo por el que juegos de esta calidad tienen un precio tan alto y es simplemente porque los desarrolladores deben invertir una gran cantidad de dinero en un producto increíble.'),
(44, 'Call of Duty BOCW', 'Call of Duty: Black Ops Cold War XBOX LIVE Key SPAIN', 'oferta', 30, 'img/Call of Duty BOCW.jpg', 'Black Ops Cold War arroja a los fans a las profundidades de la frágil batalla geopolítica de la Guerra Fría del comienzo de los años 80.  Ve cara a cara figuras históricas y duras verdades mientras batallas por el mundo en localizaciones icónicas como Berlín del Este, Vietnam, el cuartel general soviético de la KGB y muchos más.  Como agente de élite, sigue el rastro de una figura sombría en una misión para desestabilizar el equilibrio global de poder y cambiar el curso de la historia. Desciende al oscuro centro de una conspiración global junto a los personajes icónicos Woods, Mason y Hudson, más un nuevo elenco de agentes que tratan de detener un complot que lleva décadas forjándose.  Además de la campaña, Cold War trae un arsenal de armas y equipo a la nueva generación de experiencias multijugador y de zombis.'),
(45, 'Fallout 4 GOTY', 'Fallout 4 (GOTY) Steam Clave GLOBAL', 'juego', 9, 'img/Fallout 4 GOTY.jpg', '¿Echabas de menos el Yermo? Fallout 4: Game of the Year Edition key te lleva de vuelta en un instante. Bethesda se ha superado a sí misma: el juego te sumerge en sus excepcionales gráficos y varios modos de juego. Prueba la mejorada Fallout 4 GOTY key para lo que seguramente sea una de las aventuras post-apocalípticas mejor creadas de la historia. Explora el Yermo con varios objetivos en mente totalmente diferentes. ¡Buena suerte!  Cuando decidas coger la Fallout 4 key te darás cuenta de que es la mejor decisión de tu vida gaming hasta ahora, ya que garantiza una casi infinita diversión.  Utilizar tu Fallout4: Game of the Year Edition key desvela las últimas mejoras al juego (incluyendo el modo Supervivencia), mejoras gráficas, la habilidad de jugar Mods gratis en el PC y consolas, además de las expansiones oficiales.'),
(46, 'Forza Horizon 4', 'Forza Horizon 4 (PC/Xbox One) Xbox Live Clave GLOBAL', 'oferta', 19, 'img/Forza Horizon 4.jpg', 'Forza Horizon 4 key desbloquea el onceavo título del simulador de carreras desarrollado por Playground Games. Viaja la representación de ficción de mundo abierto del Reino Unido, crea tus propias carreras, compra casas in-game y desbloquea varios objetos y habilidades durante el camino. ¡Es un juego de carreras que no te puedes perder!  Características geniales Compra Forza Horizon 4 key y pilota más de 450 coches licenciados y disfruta de los ambientes cambiantes con la adición de cuatro estaciones. Las estaciones, compartidas por todo el mundo, cambian cada semana, y los jugadores serán informados de ello dentro del juego con una cuenta atrás así como una pequeña cinematográfica enseñando el cambio de una estación a la siguiente.  Estaciones dinámicas Cada nueva estación ofrecerá nuevas adiciones y nuevos retos para todos. Los lagos se congelarán y lo harán pilotable, sin embargo, las carreteras se volverán más peligrosas y derrapantes; y estas son solo algunas de las sorpresas de Forza Horizon 4 key.'),
(47, 'RE Village', 'Resident Evil Village / Resident Evil 8 Código de Steam GLOBAL', 'oferta', 39, 'img/RE Village.jpg', '¡Las pesadillas del pasado vuelven a perseguirte! Vuelve a convertirte en Ethan Winters, el protagonista del aclamado Resident Evil 7: Biohazard, y adéntrate en una misteriosa aldea llena de terrores procedentes de las más profundas fosas del infierno. Esta nueva entrega principal de la famosa franquicia Resident Evil de Capcom te hará chillar de terror mientras recorres los retorcidos pasadizos del castillo y el pueblo que lo rodea, armado únicamente con tu fiel arma. Años después de los sucesos de RE7: Biohazard, Ethan y su esposa Mia intentan vivir una vida tranquila y pacífica, pero la tragedia llega cuando su hija les es arrebatada repentinamente. Desesperado por encontrar respuestas, Ethan sigue todas las pistas hasta llegar a un pueblo envuelto en la oscuridad, gobernado por una siniestra mujer y sus hijas. Compra el Código de Steam de Resident Evil Village, sumérgete en la locura del survival horror y desentraña los secretos de lo sobrenatural.'),
(48, 'Watch Dogs Legion', 'Watch Dogs: Legion Uplay Clave EUROPA', 'juego', 26, 'img/Watch Dogs Legion.jpg', '¡Fans de la ya bien establecida franquicia cibernética están de enhorabuena! Watch Dogs vuelve con ganas, o mejor dicho, un clandestino susurro de revolución. Compra Watch Dogs: Legion key y pon el pie en las calles de un futurista Londres, reúne un grupo de leales compañeros (o peones para tus planes) ¡y recupera la ciudad! La revolución puede ser un concepto antiguo, pero ahora es hora de hacerlo viral.  Equipo sin fin ¿Recuerdas cuando tener 10 compañeros parecía mucho e incluso excesivo? Bueno, ¡imagina tener a toda la ciudad como potencial aliado! El juego hace gala de la habilidad de reclutar a cualquiera de las personas que encuentres por la calle. Así que, si alguna vez has querido salvar al mundo con tu propio equipo de frikis y raritos, compra Watch Dogs: Legion key ¡y hazlo posible! Tal vez te interese más demostrar la superioridad de gente noble… En cualquier caso, los personajes que reclutes tendrán cada uno sus propias habilidades y motivaciones, haciendo de su aportación a la revolución algo totalmente único.'),
(49, 'The Witcher 3 WH', 'The Witcher 3: Wild Hunt GOTY GOG.com Clave GLOBAL', 'juego', 15, 'img/The Witcher 3 WH.jpg', 'The Witcher 3: Wild Hunt — Game of the Year Edition key ofrece un RPG de acción de mundo abierto que incluye el juego base, ¡además de todo el contenido adicional hasta la fecha! Ya seas un fan acérrimo, o simplemente un novato, tenemos claro que te va a encantar, ¡y tener todo el contenido desde el principio es totalmente necesario para tener la experiencia completa!   Game of the Year Edition key incluye: • Expansiones Hearts of Stone y Blood & Wine, alargando el mundo explorable más de un tercio, ¡así como 50 horas de historia extra! • ¡Todo el contenido lanzado hasta la fecha! Esto incluye armas, armaduras, modos de juegos, misiones secundarias y todo lo que se ha creado para mejorar tu experiencia. • Actualizaciones técnicas y mejoras visuales, así como una nueva interfaz, completamente recreada basada en feedback del juego.'),
(50, 'Hollow Knight', 'Hollow Knight Código de Steam GLOBAL', 'juego', 15, 'img/Hollow Knight.jpg', '¡Los juegos de aventuras en 2D no están muertos! ¡Ni de lejos! ¿Quieres pruebas? ¡Hollow Knight!  Los desarrolladores Team Cherry han hecho un excelente trabajo creando un mundo más allá de la imaginación, ¡especialmente si tenemos en cuenta que este equipo está formado por sólo 3 personas!  Un amplio mundo ¡Compra Hollow Knight Steam key y descubre un mundo gigantesco! Al contrario que la mayoría de juegos indies, este no puede ser terminado en unas pocas horas, ¡ya que solo explorar todo el mundo te llevara días! Además, no puedes simplemente explorar todo el mapa conforme empiezas, ya que tendrás que encontrar específicas mejoras y amplificadores que te permitan alcanzar lugares que no podías alcanzar antes.'),
(51, 'Days Gone', 'Days Gone Código de Steam GLOBAL', 'juego', 29, 'img/Days Gone.jpg', '¿Sobrevivirás a los horrores de un mundo moribundo o tu búsqueda de una razón para vivir será en vano? Pon a prueba tu determinación en la nueva entrega de SIE Bend Studio y Sony Interactive Entertainment que combina la acción y la aventura con elementos del género de supervivencia: ¡Days Gone! Adéntrate en un mundo postapocalíptico, cambiado para siempre por una pandemia global que ha convertido a la mayor parte de la humanidad en criaturas nocturnas incontrolables y violentas, más conocidas como Freakers. Conviértete en un cazarrecompensas, busca recursos en asentamientos abandonados o abraza a tus compañeros supervivientes, haz un intento de comercio justo y recurre a la violencia si es necesario. Lo que tenías en tu vida anterior se ha perdido, pero eso no significa que no puedas empezar de nuevo. Compra el código de Steam de Days Gone y encuentra la esperanza en un futuro sombrío que se empeña en acabar con tu voluntad.'),
(52, 'Resident Evil 2', 'Resident Evil 2 / Biohazard RE:2 Steam Key EUROPE', 'juego', 16, 'img/Resident Evil 2.jpg', '25 de Enero de 2019, este el dia que marca el retorno de un juego legendario en este nueva y mejorada version. Resident Evil 2 Remake ofrece un moderno giro al clásico de 1998 de Capcom y, aunque se le llame Remake, no significa que haya copiado entero, si no que pequeños fragmentos de la historia y la jugabilidad han sido mejorados para eliminar las imperfecciones que el juego original tenia y usar de la mejor forma posible el poderoso motor gráfico de RE. El argumento, como en el juego original, sigue la historia de dos protagonistas principales con historias separadas. Lo que debes saber es que estas historias no se cruzan entre ellas, sino más bien ocurren en diferentes momentos en el tiempo, con una de ellas actuando como precuela de la otra. Esto significa que comprando Resident Evil 2 Remake no solamente estás pagando por mejores gráficos y sonidos, si no que estas consiguiendo una completa experiencia nueva, ya que durante la historia tendrás la oportunidad de comprobar las perspectivas de personajes secundarios.  Dicho todo, este juego parece convertirse en una revolución en la industria de los videojuegos y ahora tienes la oportunidad de disfrutar esta experiencia.'),
(53, 'Deathloop', 'Deathloop (PC) Steam Código GLOBAL', 'juego', 59, 'img/Deathloop.jpg', 'Los desarrolladores de Arkane Studios y la editorial Bethesda trabajaron mano a mano para traerte una experiencia de FPS única; ambientada en el mundo ficticio de la isla de Blackreef, donde asesinos luchan entre ellos para determinar el futuro de la isla. Asume el papel de Colt que está atrapado en un bucle temporal, condenado a repetir el mismo día por el resto de la eternidad. ¿No suena divertido? Compra el Código de Deathloop de Steam para ser testigo de la brillantez que hay detrás de una premisa de juego inusual: una jugabilidad atractiva, un diseño fascinante y mucho más! ¿Tienes las agallas para revivir el día y hacer las cosas perfectamente bien para dar forma al destino de Blackreef? ¿Qué características tiene el juego Deathloop? El juego innovador es el núcleo de la extraordinaria experiencia de Deathloop. Acción trepidante, una premisa única, personajes multidimensionales y más características alucinantes.  • Un arte increible. Entra en un mundo donde el arte te quita el aliento, desde los más pequeños detalles hasta la gama de colores crean una atmósfera y un estado de ánimo específicos; • Elementos de FPS. Es un FPS, así que espera muchos combates donde tienes que usar tanto la defensa como la ofensiva para derrotar a tus oponentes; • Blackreef. Entra en un mundo retro inspirado en los 60 y consumido por la inevitable decadencia; • Adaptarse es la clave. Prisionero en un bucle temporal, muere una y otra vez para aprender de tus errores y llevar a cabo tu misión; • Deathloop al major precio.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `usuario` varchar(20) DEFAULT NULL,
  `pass` varchar(20) DEFAULT NULL,
  `tipo` varchar(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id`, `usuario`, `pass`, `tipo`) VALUES
(1, 'antonio', '12345', 'admin'),
(2, 'santiago', '54321', 'admin'),
(3, 'villa', '123456', 'usuario'),
(4, 'sebastian', 'villa123', 'usuario'),
(5, 'villaantoniosantiago', '12345', 'usuario'),
(7, 'juan', '12345', 'usuario'),
(8, 'felipe', '123', 'usuario'),
(9, 'nuevousuario', '123', 'usuario');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `carrusel`
--
ALTER TABLE `carrusel`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `productos`
--
ALTER TABLE `productos`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `carrusel`
--
ALTER TABLE `carrusel`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT de la tabla `productos`
--
ALTER TABLE `productos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=54;

--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
